apiVersion: apps/v1
kind: Deployment
metadata:
  name: idgenerator
  namespace: applications
  labels:
    app: idgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idgenerator
  template:
    metadata:
      labels:
        app: idgenerator
    spec:
      containers:
      - name: idgenerator
        image: pcex2022/idgenerator:v1.0.0
        ports:
        - containerPort: 2020
---
apiVersion: v1
kind: Service
metadata:
  name: idgenerator
  namespace: applications
spec:
  type: ClusterIP
  selector:
    app: idgenerator
  ports:
    - port: 2020